runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
  GOOGLE_CLOUD_REGION: "us-central1"

instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 5
  min_idle_instances: 0
  max_idle_instances: 1
  target_cpu_utilization: 0.65

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto 